"""empty message

Revision ID: 623efe22c3d0
Revises: 9e26e992851c
Create Date: 2022-05-31 17:36:00.629667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623efe22c3d0'
down_revision = '9e26e992851c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'created_at')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
